"""adiciona data_nascimento e exclusao_solicitada_em em usuario

Revision ID: 54b69fafad49
Revises: 0bbcb36c145e
Create Date: 2026-09-14 11:31:01.733255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '54b69fafad49'
down_revision: Union[str, None] = '0bbcb36c145e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('data_nascimento', sa.Date(), nullable=True))
    op.add_column('usuario', sa.Column('exclusao_solicitada_em', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'exclusao_solicitada_em')
    op.drop_column('usuario', 'data_nascimento')
    # ### end Alembic commands ###
