"""schema inicial

Revision ID: afc62eb8476b
Revises: 
Create Date: 2026-09-10 20:11:39.485826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'afc62eb8476b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=50), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('curriculo',
    sa.Column('id_curriculo', sa.UUID(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('data_upload', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status_processamento', sa.String(length=50), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_curriculo')
    )
    op.create_table('vaga',
    sa.Column('id_vaga', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('requisitos', sa.Text(), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_vaga')
    )
    op.create_table('analise',
    sa.Column('id_analise', sa.UUID(), nullable=False),
    sa.Column('id_curriculo', sa.UUID(), nullable=False),
    sa.Column('id_vaga', sa.UUID(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('pontuacao', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_analise', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_curriculo'], ['curriculo.id_curriculo'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_vaga'], ['vaga.id_vaga'], ),
    sa.PrimaryKeyConstraint('id_analise')
    )
    op.create_table('candidato',
    sa.Column('id_candidato', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('formacao', sa.Text(), nullable=True),
    sa.Column('experiencia_profissional', sa.Text(), nullable=True),
    sa.Column('habilidades', sa.Text(), nullable=True),
    sa.Column('id_curriculo', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_curriculo'], ['curriculo.id_curriculo'], ),
    sa.PrimaryKeyConstraint('id_candidato'),
    sa.UniqueConstraint('id_curriculo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidato')
    op.drop_table('analise')
    op.drop_table('vaga')
    op.drop_table('curriculo')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
