"""schema inicial

Revision ID: db04b235405e
Revises: 20260911_01
Create Date: 2026-09-11 18:00:11.079124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'db04b235405e'
down_revision: Union[str, None] = '20260911_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
